package vstorage

import "net/http"

func cephOperations() []operation {
	operations := []operation{
		{Parent: "bucket", Use: "list", Short: "List HAN02/HCM04 buckets", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}", Paths: []pathParameter{projectID}, Queries: []queryParameter{{WireName: "limit", Flag: "limit", Usage: "Maximum number of buckets"}}},
		{Parent: "bucket", Use: "create", Short: "Create a HAN02/HCM04 bucket", Method: http.MethodPost, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}", Paths: []pathParameter{projectID, bucket}, Mutation: true},
		{Parent: "bucket", Use: "delete", Short: "Delete a HAN02/HCM04 bucket", Method: http.MethodDelete, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}", Paths: []pathParameter{projectID, bucket}, Mutation: true, Destructive: true},
		{Parent: "bucket", Use: "get", Short: "Get HAN02/HCM04 bucket details", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/{bucket}/details", Paths: []pathParameter{projectID, bucket}},
		{Parent: "bucket", Use: "get-acl", Short: "Get a HAN02/HCM04 bucket ACL", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/acl", Paths: []pathParameter{projectID, bucket}},
		{Parent: "bucket", Use: "update-acl", Short: "Update a HAN02/HCM04 bucket ACL", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/acl", Paths: []pathParameter{projectID, bucket}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket", Use: "get-cors", Short: "Get HAN02/HCM04 bucket CORS configuration", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/cors", Paths: []pathParameter{projectID, bucket}},
		{Parent: "bucket", Use: "update-cors", Short: "Replace HAN02/HCM04 bucket CORS configuration", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/cors", Paths: []pathParameter{projectID, bucket}, Body: requiredArrayBody, Mutation: true},
		{Parent: "bucket", Use: "delete-cors", Short: "Delete HAN02/HCM04 bucket CORS configuration", Method: http.MethodDelete, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/cors", Paths: []pathParameter{projectID, bucket}, Mutation: true, Destructive: true},
		{Parent: "bucket", Use: "get-encryption", Short: "Get HAN02/HCM04 bucket encryption configuration", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/encryption", Paths: []pathParameter{projectID, bucket}},
		{Parent: "bucket", Use: "update-encryption", Short: "Update HAN02/HCM04 bucket encryption configuration", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/encryption", Paths: []pathParameter{projectID, bucket}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket", Use: "list-lifecycle-rules", Short: "List HAN02/HCM04 bucket lifecycle rules", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/lifecycle_rules", Paths: []pathParameter{projectID, bucket}},
		{Parent: "bucket", Use: "create-lifecycle-rule", Short: "Create a HAN02/HCM04 bucket lifecycle rule", Method: http.MethodPost, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/lifecycle_rules", Paths: []pathParameter{projectID, bucket}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket", Use: "get-lifecycle-rule", Short: "Get a HAN02/HCM04 bucket lifecycle rule", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/lifecycle_rules/{rule_name}", Paths: []pathParameter{projectID, bucket, ruleName}},
		{Parent: "bucket", Use: "update-lifecycle-rule", Short: "Update a HAN02/HCM04 bucket lifecycle rule", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/lifecycle_rules/{rule_name}", Paths: []pathParameter{projectID, bucket, ruleName}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket", Use: "delete-lifecycle-rule", Short: "Delete a HAN02/HCM04 bucket lifecycle rule", Method: http.MethodDelete, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/lifecycle_rules/{rule_name}", Paths: []pathParameter{projectID, bucket, ruleName}, Mutation: true, Destructive: true},
		{Parent: "bucket", Use: "list-notifications", Short: "List HAN02/HCM04 bucket notifications", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/notification", Paths: []pathParameter{projectID, bucket}},
		{Parent: "bucket", Use: "create-notification", Short: "Create a HAN02/HCM04 bucket notification", Method: http.MethodPost, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/notification", Paths: []pathParameter{projectID, bucket}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket", Use: "get-notification", Short: "Get a HAN02/HCM04 bucket notification", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/notification/{id}", Paths: []pathParameter{projectID, bucket, noticeID}},
		{Parent: "bucket", Use: "update-notification", Short: "Update a HAN02/HCM04 bucket notification", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/notification/{id}", Paths: []pathParameter{projectID, bucket, noticeID}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket", Use: "delete-notification", Short: "Delete a HAN02/HCM04 bucket notification", Method: http.MethodDelete, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/notification/{id}", Paths: []pathParameter{projectID, bucket, noticeID}, Mutation: true, Destructive: true},
		{Parent: "bucket", Use: "get-object-lock", Short: "Get HAN02/HCM04 bucket object-lock configuration", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/object_lock", Paths: []pathParameter{projectID, bucket}},
		{Parent: "bucket", Use: "update-object-lock", Short: "Update HAN02/HCM04 bucket object-lock configuration", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/object_lock", Paths: []pathParameter{projectID, bucket}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket", Use: "get-policy", Short: "Get a HAN02/HCM04 bucket policy", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/policy", Paths: []pathParameter{projectID, bucket}},
		{Parent: "bucket", Use: "update-policy", Short: "Update a HAN02/HCM04 bucket policy", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/policy", Paths: []pathParameter{projectID, bucket}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket", Use: "delete-policy", Short: "Delete a HAN02/HCM04 bucket policy", Method: http.MethodDelete, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/policy", Paths: []pathParameter{projectID, bucket}, Mutation: true, Destructive: true},
		{Parent: "bucket", Use: "get-versioning", Short: "Get HAN02/HCM04 bucket versioning configuration", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/versioning", Paths: []pathParameter{projectID, bucket}},
		{Parent: "bucket", Use: "update-versioning", Short: "Update HAN02/HCM04 bucket versioning configuration", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/versioning", Paths: []pathParameter{projectID, bucket}, Body: requiredObjectBody, Mutation: true},

		{Parent: "bucket/object", Use: "list", Short: "List objects in a HAN02/HCM04 bucket", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}", Paths: []pathParameter{projectID, bucket}, Queries: []queryParameter{{WireName: "limit", Flag: "limit", Usage: "Maximum number of objects"}, {WireName: "marker", Flag: "marker", Usage: "Pagination marker"}, {WireName: "prefix", Flag: "prefix", Usage: "Object-key prefix"}, {WireName: "show_version", Flag: "show-version", Usage: "Whether to include object versions"}, {WireName: "version_id_marker", Flag: "version-id-marker", Usage: "Version pagination marker"}}},
		{Parent: "bucket/object", Use: "list-directories", Short: "List directories in a HAN02/HCM04 bucket", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/directories", Paths: []pathParameter{projectID, bucket}, Queries: []queryParameter{{WireName: "prefix", Flag: "prefix", Usage: "Directory prefix"}}},
		{Parent: "bucket/object", Use: "create-directory", Short: "Create a directory in a HAN02/HCM04 bucket", Method: http.MethodPost, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/directories", Paths: []pathParameter{projectID, bucket}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket/object", Use: "delete-directory", Short: "Delete a directory from a HAN02/HCM04 bucket", Method: http.MethodDelete, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/directories/{directory}", Paths: []pathParameter{projectID, bucket, directory}, Body: requiredObjectBody, Mutation: true, Destructive: true},
		{Parent: "bucket/object", Use: "delete", Short: "Delete an object from a HAN02/HCM04 bucket", Method: http.MethodDelete, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}", Paths: []pathParameter{projectID, bucket, object}, Body: requiredObjectBody, Mutation: true, Destructive: true},
		{Parent: "bucket/object", Use: "get-acl", Short: "Get a HAN02/HCM04 object ACL", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/acls", Paths: []pathParameter{projectID, bucket, object}, Queries: []queryParameter{versionIDQuery}},
		{Parent: "bucket/object", Use: "update-acl", Short: "Update a HAN02/HCM04 object ACL", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/acls", Paths: []pathParameter{projectID, bucket, object}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket/object", Use: "copy", Short: "Copy a HAN02/HCM04 object", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/copy", Paths: []pathParameter{projectID, bucket, object}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket/object", Use: "get", Short: "Get HAN02/HCM04 object details", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/details", Paths: []pathParameter{projectID, bucket, object}, Queries: []queryParameter{versionIDQuery}},
		{Parent: "bucket/object", Use: "generate-download-url", Short: "Generate a HAN02/HCM04 object download URL", Method: http.MethodPost, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/download_tempurls", Paths: []pathParameter{projectID, bucket, object}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket/object", Use: "get-metadata", Short: "Get HAN02/HCM04 object metadata", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/metadata", Paths: []pathParameter{projectID, bucket, object}},
		{Parent: "bucket/object", Use: "update-metadata", Short: "Update HAN02/HCM04 object metadata", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/metadata", Paths: []pathParameter{projectID, bucket, object}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket/object", Use: "move", Short: "Move a HAN02/HCM04 object", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/move", Paths: []pathParameter{projectID, bucket, object}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket/object", Use: "delete-multipart-upload", Short: "Abort a HAN02/HCM04 multipart upload", Method: http.MethodDelete, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/multipart-manifest", Paths: []pathParameter{projectID, bucket, object}, Body: requiredObjectBody, Mutation: true, Destructive: true},
		{Parent: "bucket/object", Use: "create-multipart-upload", Short: "Initiate a HAN02/HCM04 multipart upload", Method: http.MethodPost, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/multipart-manifest", Paths: []pathParameter{projectID, bucket, object}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket/object", Use: "complete-multipart-upload", Short: "Complete a HAN02/HCM04 multipart upload", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/multipart-manifest", Paths: []pathParameter{projectID, bucket, object}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket/object", Use: "get-legal-hold", Short: "Get HAN02/HCM04 object legal-hold configuration", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/object_legal_hold", Paths: []pathParameter{projectID, bucket, object}, Queries: []queryParameter{versionIDQuery}},
		{Parent: "bucket/object", Use: "update-legal-hold", Short: "Update HAN02/HCM04 object legal-hold configuration", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/object_legal_hold", Paths: []pathParameter{projectID, bucket, object}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket/object", Use: "get-retention", Short: "Get HAN02/HCM04 object retention configuration", Method: http.MethodGet, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/object_lock", Paths: []pathParameter{projectID, bucket, object}, Queries: []queryParameter{versionIDQuery}},
		{Parent: "bucket/object", Use: "update-retention", Short: "Update HAN02/HCM04 object retention configuration", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/object_lock", Paths: []pathParameter{projectID, bucket, object}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket/object", Use: "rename", Short: "Rename a HAN02/HCM04 object", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/rename", Paths: []pathParameter{projectID, bucket, object}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket/object", Use: "generate-upload-url", Short: "Generate a HAN02/HCM04 object upload URL", Method: http.MethodPost, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/upload_tempurls", Paths: []pathParameter{projectID, bucket, object}, Body: requiredObjectBody, Mutation: true},
		{Parent: "bucket/object", Use: "rollback-version", Short: "Restore a HAN02/HCM04 object version as current", Method: http.MethodPut, Path: "/api/v1/ceph/projects/{project_id}/buckets/{bucket}/objects/{object}/versions/{version_id}", Paths: []pathParameter{projectID, bucket, object, versionID}, Mutation: true, Destructive: true},
	}
	for i := range operations {
		operations[i].Extra = vstorageExtra{Family: cephFamily}
	}
	return operations
}
